baseURL = "https://laureetbastien.site"
languageCode = "fr-fr"
title = "Laure et Bastien se marient"
theme = "ananke"
publishDir = "."

MetaDataFormat = "yaml"
DefaultContentLanguage = "fr"
SectionPagesMenu = "main"

[params]  
  background_color_class = "bg-dark-blue"  
  recent_posts_number = 2